global using Microsoft.AspNetCore.Components;
global using BasicBlazorLibrary.Components.AutoCompleteHelpers;
global using BasicBlazorLibrary.Components.ComboTextboxes;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.CollectionClasses;
global using MealPlanner.CoreLibrary.ViewModels;
global using rr = BasicBlazorLibrary.Components.CssGrids.RowColumnHelpers;
global using BasicBlazorLibrary.Components.BaseClasses;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using MealPlanner.CoreLibrary.Models;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using MealPlanner.CoreLibrary.Services;
global using CommonBasicLibraries.BasicUIProcesses;
global using System.Diagnostics.CodeAnalysis;